version: '3.8'
services:
  api:
    build:
      context: .
    image: tfs-api
    container_name: tfs-api
    restart: always
    command: npm run start:prod
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app/src:ro
    environment:
      PORT:
      NODE_ENV:
      TZ:
      LOG_LEVEL:
      REDACT_LOGS:
      SINGLE_LINE_LOG_FORMAT:
      SWAGGER_USER:
      SWAGGER_PASSWORD:
      API_KEY:
      ACBS_BASE_URL:
      ACBS_MAX_REDIRECTS:
      ACBS_TIMEOUT:
      ACBS_USE_RETURN_EXCEPTION_HEADER:
      ACBS_AUTHENTICATION_API_KEY:
      ACBS_AUTHENTICATION_API_KEY_HEADER_NAME:
      ACBS_AUTHENTICATION_BASE_URL:
      ACBS_AUTHENTICATION_CLIENT_ID:
      ACBS_AUTHENTICATION_ID_TOKEN_CACHE_TTL_IN_MILLISECONDS:
      ACBS_AUTHENTICATION_LOGIN_NAME:
      ACBS_AUTHENTICATION_MAX_REDIRECTS:
      ACBS_AUTHENTICATION_MAX_NUMBER_OF_RETRIES:
      ACBS_AUTHENTICATION_PASSWORD:
      ACBS_AUTHENTICATION_RETRY_DELAY_IN_MILLISECONDS:
      ACBS_AUTHENTICATION_TIMEOUT:
      APIM_MDM_URL:
      APIM_MDM_KEY:
      APIM_MDM_VALUE:
      APIM_MDM_MAX_REDIRECTS:
      APIM_MDM_TIMEOUT:
      GIFT_API_URL:
      GIFT_API_KEY:
      GIFT_API_KEY_HEADER_NAME:
      GIFT_API_MAX_REDIRECTS:
      GIFT_API_TIMEOUT:


    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${PORT}']
      retries: 3
      interval: 60s
      timeout: 10s
      start_period: 40s
