import { UKEFID } from '../ukef-id.constant';

const CURRENCY_VALIDATION = {
  MIN_LENGTH: 3,
  MAX_LENGTH: 3,
};

/**
 * Date string validation
 * E.g: 2025-01-02
 */
const DATE_STRING = {
  MIN_LENGTH: 10,
  MAX_LENGTH: 10,
};

const FEE_TYPE_CODE = {
  MIN_LENGTH: 3,
  MAX_LENGTH: 3,
};

const ROLE_CODE = {
  MIN_LENGTH: 1,
  MAX_LENGTH: 50,
};

/**
 * Maximum monetary amount.
 * This is used for any monetary "amount" field.
 */
const MAX_MONETARY_AMOUNT = Number.MAX_SAFE_INTEGER;

export const VALIDATION = {
  CURRENCY: CURRENCY_VALIDATION,
  DATE_STRING,
  FACILITY: {
    OVERVIEW: {
      CURRENCY: CURRENCY_VALIDATION,
      DEAL_ID: UKEFID.VALIDATION,
      FACILITY_AMOUNT: { MIN: 1, MAX: MAX_MONETARY_AMOUNT },
      FACILITY_ID: UKEFID.VALIDATION,
      FACILITY_NAME: { MIN_LENGTH: 1, MAX_LENGTH: 35 },
      OBLIGOR_URN: { MIN_LENGTH: 8, MAX_LENGTH: 8 },
      PRODUCT_TYPE_CODE: { MIN_LENGTH: 3, MAX_LENGTH: 30 },
    },
  },
  COUNTERPARTY: {
    COUNTERPARTY_URN: { MIN_LENGTH: 8, MAX_LENGTH: 8 },
    ROLE_CODE,
    SHARE_PERCENTAGE: { MIN: 0.1, MAX: 100 },
  },
  FEE_TYPE_CODE,
  FIXED_FEE: {
    AMOUNT_DUE: { MIN: 1, MAX: MAX_MONETARY_AMOUNT },
    CURRENCY: CURRENCY_VALIDATION,
    DESCRIPTION: { MIN_LENGTH: 1, MAX_LENGTH: 128 },
    FEE_TYPE_CODE,
  },
  MAX_MONETARY_AMOUNT,
  OBLIGATION: {
    CURRENCY: CURRENCY_VALIDATION,
    OBLIGATION_AMOUNT: { MIN: 1, MAX: MAX_MONETARY_AMOUNT },
    OBLIGATION_SUBTYPE_CODE: { MIN_LENGTH: 1, MAX_LENGTH: 30 },
  },
  REPAYMENT_PROFILE: {
    NAME: { MIN_LENGTH: 1, MAX_LENGTH: 120 },
    ALLOCATION: {
      AMOUNT: { MIN: 0, MAX: MAX_MONETARY_AMOUNT },
    },
  },
};
