export enum BundleStatusCodeEnum {
  PENDING_INPUT_WITH_DRAFTS = '10',
  PENDING_INPUT = '15',
  PENDING_APPROVAL = '20',
  APPROVED = '25',
  DENIED = '30',
  PENDING_POSTING = '35',
  CURRENTING_POSTING = '40',
  POSTED = '50',
  POSTING_ERROR = '55',
  HISTORY_POSTED = '80',
  HISTORY_CANCELLED = '85',
  CANCELLED = '90',
}
