import { ApiProperty } from '@nestjs/swagger';
import { ENUMS } from '@ukef/constants';
import { DateOnlyString } from '@ukef/helpers/date-only-string.type';
import { IsEnum } from 'class-validator';

export class GetFacilityCovenantsResponseDto {
  // TO-DO: should this class refer to an array item or the whole array?
  @ApiProperty({
    readOnly: true,
    description:
      'The identifier of the covenant in ACBS. When creating a covenant an identifier from the number generator should be used (if this value is skipped it will be auto-generated by ACBS without checking if it is already used).',
  }) // TO-DO: check if the number generator is the same thing as the /numbers endpoint.
  covenantIdentifier: string;

  @ApiProperty({
    readOnly: true,
    description:
      'The covenant type code: 43 for a UK Contract Value covenant, 46 for a Chargable Amount covenant, and 47 for a chargable Amount covenant not in GBP.',
  }) // TO-DO: is this an accurate interpretation of the Anypoint description?
  @IsEnum(ENUMS.COVENANT_TYPE_CODES) // TO-DO: is there any point using an enum for a GET?
  covenantType: string;

  @ApiProperty({ readOnly: true, description: 'The identifier of the facility in ACBS. This will be a 10-digit code.' })
  facilityIdentifier: string;

  @ApiProperty({
    readOnly: true,
    description: 'The identifier of the portfolio in ACBS. The UKEF portfolio is E1. The maximum number of characters allowed is 2.',
  })
  portfolioIdentifier: string;

  @ApiProperty({
    readOnly: true,
    description: 'The target amount used to determine if the covenant is in compliance or not. It is called target amount in ACBS.',
  })
  maximumLiability: number;

  @ApiProperty({
    readOnly: true,
    description: 'The covenant currency type code. The maximum number of characters allowed is 3. It is called pledge type code in ACBS.',
  })
  currency: string;

  @ApiProperty({
    readOnly: true,
    description: 'The effective date of the covenant. It is called effective date in ACBS. Note that guaranteeCommencementDate and effectiveDate are the same.',
    type: Date,
    nullable: true,
    format: 'date',
  }) // TO-DO: are we asssuming that all dates could be nullable?
  guaranteeCommencementDate: DateOnlyString | null;

  @ApiProperty({
    readOnly: true,
    description: 'The effective date of the covenant. It is called effective date in ACBS. Note that guaranteeCommencementDate and effectiveDate are the same.',
    type: Date,
    nullable: true,
    format: 'date',
  })
  effectiveDate: DateOnlyString | null;

  @ApiProperty({
    readOnly: true,
    description: 'The expiration date of the covenant. It is called expiration date in ACBS.',
    type: Date,
    nullable: true,
    format: 'date',
  })
  guaranteeExpiryDate: DateOnlyString | null;
}
