export const LOGIN_NAME_REQUEST_FIELD_NAME = 'loginName';
export const PASSWORD_REQUEST_FIELD_NAME = 'password';

export const SENSITIVE_REQUEST_FIELD_NAMES = [LOGIN_NAME_REQUEST_FIELD_NAME, PASSWORD_REQUEST_FIELD_NAME];

export const ID_TOKEN_RESPONSE_FIELD_NAME = 'id_token';

export const SENSITIVE_RESPONSE_FIELD_NAMES = [ID_TOKEN_RESPONSE_FIELD_NAME];

export const SET_COOKIE_HEADER_NAME = 'set-cookie';

export const SENSITIVE_RESPONSE_HEADER_NAMES = [SET_COOKIE_HEADER_NAME];
