# TFS-API Git Hub Actions
#####################################
# This GHA is responsible for initiating various test suites
# upon a PR creation. Following test suites are executed:
# 1. Build and start check
# 2. Unit tests (Jest)
# 3. API tests (Jest)

name: Quality Assurance - Tests
run-name: Executing test QA on ${{ github.repository }} 🚀

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/test.yml"
      - "src/**"
      - "test/**"
      - "tfs-functions/**"
      - "Dockerfile"
      - "docker-compose.yml"
      - "package*"
      - "tsconfig*"
      - "jest.config.ts"
      - "nest.cli.json"

permissions:
  contents: read

env:
  environment: "qa"
  timezone: ${{ vars.TIMEZONE }}

jobs:
  # 1. Setup test infrastructure
  setup:
    name: Infrastructure setup 🔧
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
      timezone: ${{ env.timezone }}
    steps:
      - name: Environment 🧪
        run: echo "Environment set to ${{ env.environment }}"

      - name: Timezone 🌐
        run: echo "Timezone set to ${{ env.timezone }}"

  # 2. Build and start check
  build-and-start-check:
    name: Build and Start Check 🔨
    needs: setup
    env:
      FF_GIFT_ENABLED: 'true'
    environment:
      name: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: ${{ needs.setup.outputs.timezone }}

      - name: Repository
        uses: actions/checkout@v6

      - name: Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Dependencies
        working-directory: ./
        run: npm ci --legacy-peer-deps

      - name: Build
        working-directory: ./
        run: npm run build

      - name: Start (timeout after 10 seconds)
        working-directory: ./
        run: timeout 30 npm start || [ $? -eq 124 ]
        continue-on-error: false

  # 3. API unit tests
  unit-tests-ff-enabled:
    name: Unit (Feature flag enabled) 👷
    needs: [setup, build-and-start-check]
    env:
      FF_GIFT_ENABLED: 'true'
    environment:
      name: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: ${{ needs.setup.outputs.timezone }}

      - name: Repository
        uses: actions/checkout@v6

      - name: Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Dependencies
        working-directory: ./
        run: npm ci --legacy-peer-deps

      - name: Execute
        working-directory: ./
        run: npm run unit-test:ff-true

  # 4. Unit tests with feature flag disabled
  unit-tests-ff-disabled:
    name: Unit (Feature flag disabled) 👷
    needs: [setup, build-and-start-check]
    env:
      FF_GIFT_ENABLED: 'false'
    environment:
      name: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: ${{ needs.setup.outputs.timezone }}

      - name: Repository
        uses: actions/checkout@v6

      - name: Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Dependencies
        working-directory: ./
        run: npm ci --legacy-peer-deps

      - name: Execute
        working-directory: ./
        run: npm run unit-test:ff-false

  # 5. Functions unit tests
  functions-unit-tests:
    name: Functions Unit 👷
    needs: [setup, build-and-start-check]
    environment:
      name: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: ${{ needs.setup.outputs.timezone }}

      - name: Repository
        uses: actions/checkout@v6

      - name: Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Dependencies
        working-directory: ./
        run: npm ci --legacy-peer-deps

      - name: Execute
        working-directory: ./tfs-functions
        run: npm run unit-test

  # 6. API tests
  api-tests:
    name: API (ACBS) 👷
    needs: [setup, build-and-start-check]
    environment:
      name: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: ${{ needs.setup.outputs.timezone }}

      - name: Repository
        uses: actions/checkout@v6

      - name: Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Dependencies
        working-directory: ./
        run: npm ci --legacy-peer-deps

      - name: Execute
        working-directory: ./
        run: npm run api-test:acbs

  # 7. GIFT API tests
  api-tests-gift:
    name: API (GIFT, feature flag enabled) 👷
    needs: [setup, build-and-start-check]
    env:
      FF_GIFT_ENABLED: 'true'
    environment:
      name: ${{ needs.setup.outputs.environment }}
    strategy:
      matrix:
        test_file:
          - test/gift/create-facility-business-calendars-convention-error-handling.api-test.ts
          - test/gift/create-facility-validation-fixed-fees.api-test.ts
          - test/gift
    runs-on: ubuntu-latest
    steps:
      - name: Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: ${{ needs.setup.outputs.timezone }}

      - name: Repository
        uses: actions/checkout@v6

      - name: Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Dependencies
        working-directory: ./
        run: npm ci --legacy-peer-deps

      - name: Execute
        working-directory: ./
        env:
          FF_GIFT_ENABLED: 'false'
          GIFT_HTTP_VERSION: ${{ vars.GIFT_HTTP_VERSION }}
        run: |
          if [[ "${{ matrix.test_file }}" == "test/gift" ]]; then
            npx jest --coverage --selectProjects=API-FF=true --testPathPatterns="gift" --testPathIgnorePatterns="create-facility-business-calendars-convention-error-handling.api-test.ts|create-facility-validation-fixed-fees.api-test.ts"
          else
            npx jest --coverage --selectProjects=API-FF=true --runTestsByPath "${{ matrix.test_file }}"
          fi

  # 8. Feature Flag Disabled API tests
  api-tests-ff-disabled:
    name: API (Feature flag disabled) 👷
    needs: [setup, build-and-start-check]
    environment:
      name: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: ${{ needs.setup.outputs.timezone }}

      - name: Repository
        uses: actions/checkout@v6

      - name: Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Dependencies
        working-directory: ./
        run: npm ci --legacy-peer-deps

      - name: Execute
        working-directory: ./
        run: npm run api-test:ff-false
